# Generated by Django 5.2.4 on 2025-09-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_quicktip'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
