# Generated by Django 5.2.4 on 2025-09-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_farmer_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='farmer',
            table='core_farmers',
        ),
    ]
