# Generated by Django 5.2.4 on 2025-09-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_farmer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='farmer',
            table='core_farmer',
        ),
    ]
